---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Create index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
