---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - net-tools
    - dnsutils
    - wget
    - curl
    - mc
    - rsync
