---
- name: Apply common configuration to all servers
  hosts: all
  become: yes
  roles:
    - common

- name: Configure proxy server
  hosts: proxy
  become: yes
  roles:
    - nginx_proxy

- name: Configure backend servers
  hosts: backend
  become: yes
  roles:
    - nginx_backend
